llamda base de datos para monstrar intructores y fichas
sena-proyectos/practicas-ctm pull request #23
Opened 2023-08-14 21:13 UTC by JuanPrasca

2023-08-15 13:34 UTC, ConanGH-S requested changes
Concluir cambios para hoy, urgente. Además verificar las versión más actualizadas de la master del client y server, en caso de que no sean iguales, hacer `pull`

2023-08-15 13:34 UTC, ConanGH-S commented on client/src/App.jsx
> +import { GetFichasHttp } from './api/httpRequest'
Eliminar línea

2023-08-15 13:34 UTC, ConanGH-S commented on client/src/components/Assign-class/AssignClass.jsx
> +        ficha: 247319,
¿?

2023-08-15 13:34 UTC, ConanGH-S commented on client/src/components/Assign-class/AssignClass.jsx
> +export const AssignClass = ({ fichas = [] }) => {
¿Cuál es la importancia de este parámetro?

2023-08-15 13:34 UTC, ConanGH-S commented on client/src/components/Courses/Courses.jsx
> +      ...ficha.map(item => ({
No es necesario volver a guardarlo en el array, solo mapea el State

2023-08-15 13:34 UTC, ConanGH-S commented on client/src/components/Register-student/RegisterStudent.jsx
>        const teacher = formValues.nombre_instructor_lider_inscripcion
Estás desestructurando una variable pero los otros no, es mejor realizarlo

2023-08-15 13:34 UTC, ConanGH-S commented on client/src/components/Student/Student.jsx
> +    getU
¿Por qué está separado?

2023-08-15 13:34 UTC, ConanGH-S commented on client/src/validation/RegularExpressions.js
> +// export const validate
Eliminar la línea

2023-08-15 13:34 UTC, ConanGH-S commented on server/package.json
Versión desactualizada

2023-08-15 13:34 UTC, ConanGH-S commented on server/src/controllers/email.controllers.ts
Sería mejor envolverlo en un `try-catch para manejar esos errores`, busca referencia de otros controladores para seguir la misma línea de trabajo

2023-08-15 13:34 UTC, ConanGH-S commented on server/src/middlewares/email.middleware.ts
usar `trycatch`

2023-08-15 17:57 UTC, JuanPrasca commented on server/src/middlewares/email.middleware.ts
Okkk

2023-08-15 17:57 UTC, JuanPrasca commented on server/src/controllers/email.controllers.ts
OKKK

2023-10-02 21:06 UTC, ConanGH-S commented
Cerrado por inactividad.

2023-10-02 21:06 UTC, closed without merging