Students
sena-proyectos/practicas-ctm pull request #24
Opened 2023-08-15 16:53 UTC by axelchica759

2023-08-15 16:59 UTC, lorenqg requested changes

2023-08-15 16:59 UTC, lorenqg commented on client/src/components/Form/Form.jsx
La función no se puede llamar app, no estás en ese componente

2023-08-15 16:59 UTC, lorenqg commented on client/src/main.jsx
> +
quitar salto de linea

2023-10-02 21:05 UTC, ConanGH-S commented
Sin utilidad, cerrado.

2023-10-02 21:05 UTC, closed without merging